### ISSUE TITLE
Crashes whenever loading sounds 1.18.2

### ISSUE THREAD

**Issue by Nathanael-UwU** [stashymane/extra-sounds#55] opened 2022-05-28 20:14 UTC
Minecraft: 1.18.2
Mod Loader: 0.14.6
Mod: extrasounds-2.2.1+1.18.2
Other Mods: fabric-api-0.53.3+1.18.2 (old version because optifine wont work otherwise, not the cause of the bug), modmenu-3.2.2, optifabric-1.13.0, OptiFine_1.18.2_HD_U_H7

The game crashes whenever loading and sounds from the mod only occurs when using optifabric for optifine on fabric.

Log file:
[2022-05-28-7.log](https://github.com/stashymane/extra-sounds/files/8791811/2022-05-28-7.log)

**Comment by stashymane** [comment] 2022-05-29 08:30
Duplicate of #31 - Optifine apparently mangles the way options are loaded, so it's been marked as incompatible until I work around this.

**Closed by stashymane** 2022-05-29 08:30 UTC
Labels: bug
