### ISSUE TITLE
Game fails to start, suspected mod compatibility

### ISSUE THREAD

**Issue by CornCobDog** [stashymane/extra-sounds#23] opened 2021-11-10 06:53 UTC
attached is a list of mods used and the screen shown by the game on startup
https://imgur.com/a/huXeGrf
the mod seems to work with another group of mods, though with this group, it freezes on startup

sorry if you are unable to identify the error due to a lack of logs provided, i've tried manually crashing the game, but a crash log cannot be generated

**Comment by stashymane** [comment] 2021-12-10 19:53
I tried to launch the newest builds with the list of mods provided, everything seems to be loading fine.
Try [this build for 1.17](https://github.com/stashymane/extra-sounds/actions/runs/1544702901) or [this build for 1.18](https://github.com/stashymane/extra-sounds/actions/runs/1541505412).
If the same issue occurs, please provide a log - it does not need to be a crash log, as the game technically does not crash, a regular log (`latest.log`) contains all the details required.
Closing for now, as I cannot reproduce.

**Closed by stashymane** 2021-12-10 19:53 UTC

**Comment by CornCobDog** [comment] 2021-12-13 02:49
thank you so much! i'll download the artifact and test it out
