### ISSUE TITLE
Problem with 1.3.0

### ISSUE THREAD

**Issue by ChromaPIE** [stashymane/extra-sounds#8] opened 2021-05-20 15:51 UTC
Picking up & putting down items in the inventory play no sounds, and when left click boots from the armor slot the game would crash.

Log: https://paste.ubuntu.com/p/CdKTXJ87J3/
CR: https://paste.ubuntu.com/p/Chrz4Fm89k/

**Comment by stashymane** [comment] 2021-05-20 19:39
Oopsie, forgot to do a null check on the click event, I'll release a quick workaround soon for the crash.
Regarding the sounds not playing, could you perhaps add [MixinTrace](https://modrinth.com/mod/mixintrace) to your mods and upload a log after clicking inventory items and then having the game crash? That will help me figure out what exactly differs on your setup, as I cannot reproduce this with my own set of mods.

**Comment by stashymane** [comment] 2021-05-21 10:21
I think I fixed it in [this build](https://github.com/stashymane/extra-sounds/actions/runs/863520038) - can you check whether the build in the artifacts works?

**Comment by stashymane** [comment] 2021-05-21 23:37
Seems to be resolved in 1.3.1 - please report back if the crash still occurs.

**Closed by stashymane** 2021-05-21 23:37 UTC
