### ISSUE TITLE
Crashes with OptiFabric (1.17.1)

### ISSUE THREAD

**Issue by Darutan92** [stashymane/extra-sounds#48] opened 2022-05-10 19:52 UTC
Minecraft: `1.17.1`
Mod: `-ExtraSounds2.2.1-for-1.17.1`

Crash without crash report when load game with `fabric 0.13.3 (1.17.1)`, `fabric-api-0.46.1`, `optifabric 1.12.10/1.13.0`, `optifine 1.17.1_HD_U_H1`, `cloth-config-5.3.58`, and `-ExtraSounds2.2.1-for-1.17.1`

log - https://pastebin.com/cFjdav4R

I found a [similar question](https://github.com/stashymane/extra-sounds/issues/31), [another](https://github.com/stashymane/extra-sounds/issues/42) and [another](https://github.com/Chocohead/OptiFabric/issues/663), but my english is not very good, so i understand the problem cannot be fixed?

**Comment by stashymane** [comment] 2022-05-10 20:40
The issue can definitely be fixed, however I have not had much time off work lately, hence the lack of updates. No ETA, but I'll most likely look into it the next time I'm working on ExtraSounds.
Closing this issue as it's a duplicate of #31 - please post new findings there.

**Closed by stashymane** 2022-05-10 20:40 UTC
Labels: bug
