### ISSUE TITLE
Seemingly incompatible with OptiFabric mod

### ISSUE THREAD

**Issue by NaiNonTH** [stashymane/extra-sounds#42] opened 2022-03-28 10:45 UTC
Minecraft: 1.18.2
Mod: 2.2.1

## Details
As I opened up the game inventory, the game went crash and showed me a crash report, as long as I removed the ExtraSounds mod. I've read through the log and found out that the game tried to find a file location, `dev/stashy/soundcategories/CategoryLoader`, provided from Sound Categories mod by ExtraSounds mod.

-- Copied from https://github.com/Chocohead/OptiFabric/issues/663https://github.com/Chocohead/OptiFabric/issues/663

**Log**
[latest.log](https://github.com/stashymane/extra-sounds/files/8361928/latest.log) (Also ran with `-Dextrasounds.debug=true`)

**Comment by stashymane** [comment] 2022-05-24 21:35
Forgot to manage this issue - dupe of #31, closing.

**Closed by stashymane** 2022-05-24 21:35 UTC
Labels: bug
